# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e92c05f16b19f47f201a8758efd4e47cc98f8efbe3d3323f44e3e5ed11170f55c4131f7ba2bdca4210d4ca215af4c447064e5c94b64c93175ac1e549c044c744

test:
  secret_key_base: d4ae0f609fa9d4d3130de212018a663b14664d5d95dab296c0fd31029eb53650f691ecc39c1998e70a160404a3b1ee0115144d1cf147129c7274724edac8ee7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
