CitiesMovie.create!([
  {city_id: 1, movie_id: 1},
  {city_id: 1, movie_id: 1},
  {city_id: 1, movie_id: 2},
  {city_id: 1, movie_id: 3},
  {city_id: 1, movie_id: 4},
  {city_id: 1, movie_id: 5},
  {city_id: 1, movie_id: 6},
  {city_id: 1, movie_id: 7},
  {city_id: 1, movie_id: 8},
  {city_id: 1, movie_id: 9},
  {city_id: 1, movie_id: 10},
  {city_id: 1, movie_id: 11},
  {city_id: 1, movie_id: 12},
  {city_id: 1, movie_id: 13},
  {city_id: 1, movie_id: 14},
  {city_id: 1, movie_id: 15},
  {city_id: 1, movie_id: 16},
  {city_id: 1, movie_id: 17},
  {city_id: 1, movie_id: 18},
  {city_id: 1, movie_id: 19},
  {city_id: 1, movie_id: 20},
  {city_id: 1, movie_id: 21},
  {city_id: 1, movie_id: 22},
  {city_id: 1, movie_id: 23},
  {city_id: 1, movie_id: 24},
  {city_id: 1, movie_id: 25},
  {city_id: 1, movie_id: 26},
  {city_id: 1, movie_id: 27},
  {city_id: 1, movie_id: 28},
  {city_id: 1, movie_id: 29},
  {city_id: 1, movie_id: 30},
  {city_id: 1, movie_id: 31},
  {city_id: 1, movie_id: 32},
  {city_id: 1, movie_id: 33},
  {city_id: 1, movie_id: 34},
  {city_id: 1, movie_id: 35},
  {city_id: 1, movie_id: 36},
  {city_id: 1, movie_id: 37},
  {city_id: 1, movie_id: 38},
  {city_id: 1, movie_id: 39},
  {city_id: 1, movie_id: 40},
  {city_id: 1, movie_id: 41},
  {city_id: 1, movie_id: 42},
  {city_id: 1, movie_id: 43},
  {city_id: 1, movie_id: 44},
  {city_id: 1, movie_id: 45},
  {city_id: 1, movie_id: 46},
  {city_id: 1, movie_id: 47},
  {city_id: 1, movie_id: 48},
  {city_id: 1, movie_id: 49},
  {city_id: 1, movie_id: 50},
  {city_id: 1, movie_id: 51},
  {city_id: 1, movie_id: 52},
  {city_id: 1, movie_id: 53},
  {city_id: 1, movie_id: 54},
  {city_id: 1, movie_id: 55},
  {city_id: 1, movie_id: 56},
  {city_id: 1, movie_id: 57},
  {city_id: 1, movie_id: 58},
  {city_id: 1, movie_id: 59},
  {city_id: 1, movie_id: 60},
  {city_id: 1, movie_id: 61}
])
City.create!([
  {city: "France"}
])
Movie.create!([
  {title: "THE REVENANT", distributor: "20TH CENTURY...", release_date: nil, weeks: 2, number_of_copies: 546, spectators_per_week: 841295, total_spectators: 2250728, satisfaction_rate: 0.65},
  {title: "ZOOTOPIE", distributor: "WALT DISNEY ...", release_date: nil, weeks: 3, number_of_copies: 647, spectators_per_week: 603920, total_spectators: 3189198, satisfaction_rate: 0.65},
  {title: "PATTAYA", distributor: "GAUMONT", release_date: nil, weeks: 2, number_of_copies: 341, spectators_per_week: 395969, total_spectators: 1331464, satisfaction_rate: 0.0},
  {title: "DEADPOOL", distributor: "20TH CENTURY...", release_date: nil, weeks: 4, number_of_copies: 489, spectators_per_week: 256286, total_spectators: 3306065, satisfaction_rate: 0.57},
  {title: "LES TUCHE 2 : LE REVE...", distributor: "PATHE", release_date: nil, weeks: 5, number_of_copies: 635, spectators_per_week: 222378, total_spectators: 4312292, satisfaction_rate: 0.2},
  {title: "SAINT-AMOUR", distributor: "LE PACTE", release_date: nil, weeks: 1, number_of_copies: 362, spectators_per_week: 217925, total_spectators: 217925, satisfaction_rate: 0.25},
  {title: "LA VACHE", distributor: "PATHE", release_date: nil, weeks: 3, number_of_copies: 336, spectators_per_week: 166449, total_spectators: 763357, satisfaction_rate: 0.69},
  {title: "LA CHUTE DE LONDRES", distributor: "SND", release_date: nil, weeks: 1, number_of_copies: 204, spectators_per_week: 164899, total_spectators: 164899, satisfaction_rate: 0.25},
  {title: "CELIBATAIRE, MODE D'E...", distributor: "WARNER BROS.", release_date: nil, weeks: 1, number_of_copies: 187, spectators_per_week: 154067, total_spectators: 154067, satisfaction_rate: 0.3},
  {title: "ALVIN ET LES CHIPMUNK...", distributor: "20TH CENTURY...", release_date: nil, weeks: 5, number_of_copies: 527, spectators_per_week: 117648, total_spectators: 1713178, satisfaction_rate: 0.4},
  {title: "CHOCOLAT", distributor: "GAUMONT", release_date: nil, weeks: 5, number_of_copies: 589, spectators_per_week: 93441, total_spectators: 1780187, satisfaction_rate: 0.53},
  {title: "EPERDUMENT", distributor: "STUDIOCANAL", release_date: nil, weeks: 1, number_of_copies: 201, spectators_per_week: 90282, total_spectators: 90282, satisfaction_rate: 0.26},
  {title: "AMIS PUBLICS", distributor: "LA BELLE COM...", release_date: nil, weeks: 3, number_of_copies: 496, spectators_per_week: 83106, total_spectators: 704526, satisfaction_rate: 0.47},
  {title: "LES INNOCENTES", distributor: "MARS DISTRIB...", release_date: nil, weeks: 4, number_of_copies: 314, spectators_per_week: 66528, total_spectators: 493821, satisfaction_rate: 0.68},
  {title: "HEIDI", distributor: "STUDIOCANAL", release_date: nil, weeks: 4, number_of_copies: 353, spectators_per_week: 61174, total_spectators: 612511, satisfaction_rate: 0.0},
  {title: "AVE, CESAR !", distributor: "UNIVERSAL PI...", release_date: nil, weeks: 3, number_of_copies: 305, spectators_per_week: 60350, total_spectators: 596625, satisfaction_rate: 0.2},
  {title: "JOSEPHINE S'ARRONDIT", distributor: "UGC DISTRIBU...", release_date: nil, weeks: 4, number_of_copies: 354, spectators_per_week: 58555, total_spectators: 829775, satisfaction_rate: 0.17},
  {title: "ZOOLANDER 2", distributor: "PARAMOUNT PI...", release_date: nil, weeks: 1, number_of_copies: 226, spectators_per_week: 42796, total_spectators: 42796, satisfaction_rate: 0.0},
  {title: "SPOTLIGHT", distributor: "WARNER BROS.", release_date: nil, weeks: 6, number_of_copies: 246, spectators_per_week: 41856, total_spectators: 525297, satisfaction_rate: 0.6},
  {title: "DEMAIN", distributor: "MARS DISTRIB...", release_date: nil, weeks: 14, number_of_copies: 315, spectators_per_week: 38142, total_spectators: 801361, satisfaction_rate: 0.0},
  {title: "MERCI PATRON", distributor: "JOUR2FETE", release_date: nil, weeks: 2, number_of_copies: 49, spectators_per_week: 26880, total_spectators: 75352, satisfaction_rate: 0.0},
  {title: "BELGICA", distributor: "PYRAMIDE", release_date: nil, weeks: 1, number_of_copies: 104, spectators_per_week: 22053, total_spectators: 22053, satisfaction_rate: 0.0},
  {title: "FATIMA", distributor: "PYRAMIDE", release_date: nil, weeks: 22, number_of_copies: 98, spectators_per_week: 20514, total_spectators: 331538, satisfaction_rate: 0.0},
  {title: "LES SAISONS", distributor: "PATHE", release_date: nil, weeks: 6, number_of_copies: 274, spectators_per_week: 19531, total_spectators: 910578, satisfaction_rate: 0.47},
  {title: "NAHID", distributor: "MEMENTO FILMS", release_date: nil, weeks: 2, number_of_copies: 70, spectators_per_week: 18187, total_spectators: 52484, satisfaction_rate: 0.0},
  {title: "LES DELICES DE TOKYO", distributor: "HAUT ET COURT", release_date: nil, weeks: 6, number_of_copies: 183, spectators_per_week: 16148, total_spectators: 258805, satisfaction_rate: 0.0},
  {title: "LA 5EME VAGUE", distributor: "SONY PICTURE...", release_date: nil, weeks: 6, number_of_copies: 99, spectators_per_week: 12344, total_spectators: 992496, satisfaction_rate: 0.23},
  {title: "MOONWALKERS", distributor: "MARS DISTRIB...", release_date: nil, weeks: 1, number_of_copies: 51, spectators_per_week: 10869, total_spectators: 10869, satisfaction_rate: 0.0},
  {title: "CHAIR DE POULE : LE FILM", distributor: "SONY PICTURE...", release_date: nil, weeks: 4, number_of_copies: 156, spectators_per_week: 10104, total_spectators: 321990, satisfaction_rate: 0.0},
  {title: "TOUT EN HAUT DU MONDE", distributor: "DIAPHANA", release_date: nil, weeks: 6, number_of_copies: 161, spectators_per_week: 8712, total_spectators: 165800, satisfaction_rate: 0.0}
])
